name: publish packages

on:
  push:
    tags:
        - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack -c Release
    - name: publish Samhammer.Logging
      run: dotnet nuget push "Samhammer.Logging/bin/Release/Samhammer.Logging.*.nupkg" --api-key ${NUGET_KEY} --source https://api.nuget.org/v3/index.json
      env:
        NUGET_KEY: ${{ secrets.NUGET_KEY}}
    - name: public Samhammer.Logging.Serilog
      run: dotnet nuget push "Samhammer.Logging.Serilog/bin/Release/Samhammer.logging.Serilog.*.nupkg" --api-key ${NUGET_KEY}  --source https://api.nuget.org/v3/index.json
      env:
        NUGET_KEY: ${{ secrets.NUGET_KEY}}