name: publish packages

on:
  push:
    tags:
        - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'
    - name: Build
      run: dotnet build -c Release Samhammer.Logging.sln
    - name: Pack
      run: dotnet pack -c Release --nologo
    - name: Push
      run: |
        dotnet nuget push "Samhammer.Logging/bin/Release/Samhammer.Logging.*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        dotnet nuget push "Samhammer.Logging.Serilog/bin/Release/Samhammer.logging.Serilog.*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
