name: publish packages

on:
  push:
    tags:
        - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack -c Release
    - name: publish Samhammer.Logging
      run: dotnet nuget push "Samhammer.Logging/bin/Release/Samhammer.Logging.*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
    - name: public Samhammer.Logging.Serilog
      run: dotnet nuget push "Samhammer.Logging.Serilog/bin/Release/Samhammer.logging.Serilog.*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json